---
# Initial, common, system setup steps

- name: enable sudo without tty for some ansible commands
  replace:
    path: /etc/sudoers
    regexp: '^Defaults\s*requiretty'
    replace: 'Defaults  !requiretty'
    backup: yes

- name: enable repos
  get_url:
    url: http://www.opentlc.com/download/ansible_bootcamp/repo/internal.repo
    dest: /etc//yum.repos.d/open_three-tier-app.repo
 
# - name: install base tools and packages
# Why is this here and not in the instructions to add packages?